# Generated by Django 3.1.2 on 2020-10-14 23:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_posts', through='posts.Fav', to=settings.AUTH_USER_MODEL),
        ),
    ]
