# Generated by Django 3.1.2 on 2020-10-15 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201014_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='favorites',
        ),
        migrations.DeleteModel(
            name='Fav',
        ),
    ]
